import type { EnvVarSpec } from "./types";

export const aiEnv: readonly EnvVarSpec[] = [
  {
    name: "AI_PROVIDER",
    group: "AI",
    kind: "enum",
    values: ["disabled", "anthropic", "openai", "custom", "chatgpt"],
    default: "disabled",
    doc: "AI chat-proxy provider: disabled (chat panel hidden), anthropic (Messages API), openai (Chat Completions), custom (any OpenAI-compatible baseUrl), or chatgpt (each user connects their own ChatGPT Plus/Pro subscription via Codex OAuth — billed to the user, no server API key). The admin settings page can override this at runtime.",
  },
  {
    name: "AI_API_KEY",
    group: "AI",
    kind: "string",
    secret: true,
    doc: "Provider API key for the AI chat proxy. Server-side only — never shipped to the browser. An env-provided key always wins over a key stored via the admin settings page.",
    example: "sk-...",
  },
  {
    name: "AI_BASE_URL",
    group: "AI",
    kind: "string",
    doc: "Override the provider base URL (e.g. an OpenAI-compatible gateway or self-hosted endpoint). Required for AI_PROVIDER=custom; optional otherwise.",
    example: "https://api.openai.com/v1",
  },
  {
    name: "AI_MODEL",
    group: "AI",
    kind: "string",
    doc: "Model id the chat proxy requests (e.g. claude-opus-4-8 for anthropic, gpt-4o for openai). Falls back to a provider default when unset.",
    example: "claude-opus-4-8",
  },
  {
    name: "AI_MAX_TOKENS_PER_REQUEST",
    group: "AI",
    kind: "number",
    default: "4096",
    doc: "Maximum output tokens the chat proxy requests per model call.",
  },
  {
    name: "AI_RATE_LIMIT_MAX",
    group: "AI",
    kind: "number",
    default: "60",
    doc: "Maximum AI chat requests allowed per user within AI_RATE_LIMIT_WINDOW_MS.",
  },
  {
    name: "AI_RATE_LIMIT_WINDOW_MS",
    group: "AI",
    kind: "number",
    default: "60000",
    doc: "Rolling window (ms) for the AI chat per-user rate limiter.",
  },
  {
    name: "AI_CHATGPT_CLIENT_VERSION",
    group: "AI",
    kind: "string",
    default: "0.142.5",
    doc: "Codex `client_version` sent to the ChatGPT backend (AI_PROVIDER=chatgpt). The backend gates the available model set on this — bump it toward the current Codex CLI release without a redeploy if models disappear.",
    example: "0.142.5",
  },
  {
    name: "AI_CHATGPT_MODELS",
    group: "AI",
    kind: "string",
    doc: "Comma-separated Codex model slugs offered when AI_PROVIDER=chatgpt (first is the default). Falls back to a built-in gpt-5.x list when unset.",
    example: "gpt-5.1,gpt-5.1-codex,gpt-5.2",
  },
  {
    name: "AI_CHATGPT_CLIENT_ID",
    group: "AI",
    kind: "string",
    doc: "Override the ChatGPT/Codex OAuth client id. Defaults to the public Codex CLI client. Only change if OpenAI rotates the client.",
  },
  {
    name: "AI_CHATGPT_ISSUER",
    group: "AI",
    kind: "string",
    doc: "Override the ChatGPT OAuth issuer origin (authorize/token endpoints). Defaults to https://auth.openai.com.",
  },
  {
    name: "AI_CHATGPT_REDIRECT_URI",
    group: "AI",
    kind: "string",
    doc: "OAuth redirect URI for the Codex loopback flow. Defaults to http://localhost:1455/auth/callback; the connect flow uses manual URL paste so this need not be reachable by the server.",
  },
  {
    name: "AI_CHATGPT_CODEX_BASE_URL",
    group: "AI",
    kind: "string",
    doc: "Base URL of the ChatGPT-backed Codex responses API. Defaults to https://chatgpt.com/backend-api/codex.",
  },
  {
    name: "AI_CHATGPT_SCOPE",
    group: "AI",
    kind: "string",
    doc: "OAuth scopes requested for the ChatGPT session. Defaults to 'openid profile email offline_access' (offline_access is required for refresh).",
  },
  {
    name: "AI_CHATGPT_ORIGINATOR",
    group: "AI",
    kind: "string",
    doc: "`originator` header/param value identifying the client to OpenAI. Defaults to codex_cli_rs.",
  },
];
